name: Publish
on:  
  push:
    tags:
      - '*'
jobs:
  publish:
    name: Publish to pages
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code
      uses: actions/checkout@v2
      with:
        # preserve history to be able to see latest tag
        fetch-depth: 0

    - name: Run tests
      run: go test -race -v ./...

    - name: Build pages
      run: make depl-pages

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build/gh-pages
        CLEAN: true
